"""Configuration management for OncAI."""

from __future__ import annotations

import os
import re
from enum import StrEnum
from pathlib import Path
from typing import Literal

import yaml
from dotenv import load_dotenv
from pydantic import BaseModel, Field


class LLMBackendConfig(BaseModel):
    """Configuration for a named LLM backend (connection info only)."""

    type: Literal["azure-responses", "vllm", "vllm-chat"] = Field(
        description="Backend type"
    )
    # Azure-specific
    endpoint: str | None = Field(default=None, description="Azure OpenAI endpoint URL")
    deployment: str | None = Field(
        default=None, description="Azure deployment/model name"
    )
    api_version: str = Field(
        default="2025-03-01-preview", description="Azure API version"
    )
    # vLLM-specific
    base_url: str | None = Field(default=None, description="vLLM server URL")
    model: str | None = Field(default=None, description="vLLM model name")
    # Shared
    api_key_env: str = Field(
        default="AZURE_OPENAI_API_KEY",
        description="Name of the env var holding the API key (loaded from .env)",
    )

    def resolve_api_key(self) -> str:
        """Resolve the API key from the environment variable."""
        key = os.getenv(self.api_key_env)
        if not key:
            raise ValueError(
                f"API key not found. Set {self.api_key_env} in your .env file "
                f"or as an environment variable."
            )
        return key


class OncaiConfig(BaseModel):
    """OncAI configuration settings."""

    remote_path: Path = Field(
        default=Path("oncai_data/remote"),
        description=(
            "Path to remote data. This is a plain filesystem path — for "
            "SFTP/cloud storage, mount it locally (sshfs, rclone, Box Drive) "
            "and point this at the mount. See docs/design.md."
        ),
    )
    lake_path: Path = Field(
        default=Path("oncai_data/lake"),
        description="Local mirror of remote data",
    )
    inbox_path: Path = Field(
        default=Path("oncai_data/inbox"),
        description="Drop raw CSVs here for ingestion",
    )
    db_path: Path = Field(
        default=Path("oncai_data/oncai.duckdb"),
        description="Path to DuckDB database",
    )
    llm_backends: dict[str, LLMBackendConfig] = Field(
        default_factory=dict,
        description="Named LLM backend configurations",
    )

    def get_backend(self, name: str) -> LLMBackendConfig:
        """Look up a named LLM backend. Raises ValueError if not found."""
        if name not in self.llm_backends:
            available = ", ".join(self.llm_backends.keys()) or "(none configured)"
            raise ValueError(
                f"Unknown LLM backend '{name}'. "
                f"Available backends in oncai.yaml: {available}"
            )
        return self.llm_backends[name]


def load_config(config_path: Path | None = None) -> OncaiConfig:
    """Load configuration from YAML file. Also loads .env from the same directory."""
    if config_path is None:
        config_path = Path("oncai.yaml")

    # Load .env from the same directory as the config file
    env_path = config_path.parent / ".env"
    load_dotenv(env_path)

    if config_path.exists():
        with config_path.open() as f:
            data = yaml.safe_load(f) or {}
        return OncaiConfig(**data)

    return OncaiConfig()


def save_config(config: OncaiConfig, config_path: Path | None = None) -> None:
    """Save configuration to YAML file."""
    if config_path is None:
        config_path = Path("oncai.yaml")

    data = config.model_dump(mode="json", exclude_none=True)
    # Convert Path objects to strings
    for key, value in data.items():
        if isinstance(value, Path):
            data[key] = str(value)

    with config_path.open("w") as f:
        yaml.dump(data, f, default_flow_style=False, sort_keys=False)


class IngestMode(StrEnum):
    """How a dataset folder's inbox files are turned into lake parquets.

    - DATED: ISO-prefix replay-from-scratch into a single ``<folder>.parquet``.
    - STATIC: one inbox file → one lake parquet keyed by filename stem;
      no merge across files.
    - NAMED: filename = identity (cohorts); each file is independent.
    - LAKE_ONLY: no inbox path; files arrive in the lake by other means
      (external pipelines, generated by other oncai commands).
    """

    DATED = "dated"
    STATIC = "static"
    NAMED = "named"
    LAKE_ONLY = "lake_only"


FOLDER_MODES: dict[str, IngestMode] = {
    "pathology": IngestMode.DATED,
    "fc_extractions": IngestMode.STATIC,
    "cohorts": IngestMode.NAMED,
    "runs": IngestMode.LAKE_ONLY,
}


# YYYY-MM-DD_<label>.{csv,jsonl} — label is informational; folder determines schema.
DATED_FILENAME_RE = re.compile(r"^\d{4}-\d{2}-\d{2}_.+\.(csv|jsonl)$")


def get_dataset_folders() -> list[str]:
    """Return list of known dataset folder names."""
    return list(FOLDER_MODES.keys())


def get_folders_by_mode(mode: IngestMode) -> list[str]:
    """Return folders matching *mode*."""
    return [name for name, m in FOLDER_MODES.items() if m == mode]
